### ISSUE TITLE
fika

### ISSUE THREAD

**Issue by larsbrinkhoff** [almquistj/adkpitch#2]
Hej! Vi gjorde inte upp om betalningen. Jag kan ju swisha till dig.

**Comment by almquistj** [comment]
Hej
Jag testade att maila din delphi address ifall du råkade ha passning på den. Vet inte riktigt vart det här meddelandet landar...

Hursom... visst, vill du swisha 125:- till 0721 746733 så är det välkommet. Må gott!

**Comment by larsbrinkhoff** [comment]
Fixat.

Jag har ingen tillgång till email på Delphi, men meddelanden på GitHub ser jag.
